### ISSUE TITLE
Netezza support

### ISSUE THREAD

**Issue by aaron0browne** [OHDSI/DatabaseConnector#1]
It seems like it would be fairly easy to add support for Netezza and there is an existing use case in PEDSnet. Since Netezza is based on PostgreSQL, I'm thinking it would be very similar to the redshift implementation in [connect.default](https://github.com/OHDSI/DatabaseConnector/blob/master/R/DatabaseConnector.R#L311). Thoughts?

**Comment by cgreich** [comment]
Friends:
Trying to connect to Netezza. Your block of code doesn't seem to be working with our box:
* There is no such a command as "set search_path to". Instead, it should be "set schema to". Aaron must have installed some compatibility module or so. 
* Actually, I would like to try to get around that. Instead of setting a search path or schema, I want to use the name in the queries. Why can't we do that. The syntax would be SELECT * FROM <database>.<schema>.<table>. What's wrong with that?
* We need a solution for the vocabulary. What if it doesn't live in the same schema as the data table? Or is that a requiement.

**Comment by pbr6cornell** [comment]
Vocabulary tables are part of cdm and must be in the cdm_schema.

Analysis scripts do use the 'use'/'set schema' function, and there are
specific instances where it is necessary to do so (such as for checking
existence of temp tables in oracle).

**Comment by ericaVoss** [comment]
@cgreich here we have a main Vocab that sits alone but we also embed the Vocab the CDM was run on within the CDM.  This allows your main Vocab to update while you still maintain the exact copy that built the CDM.
