### ISSUE TITLE
Support for Oracle TNSNAMES via JDBC

### ISSUE THREAD

**Issue by nixj14** [OHDSI/DatabaseConnector#11]
I'm accustomed to connecting using the Oracle Thin driver using TNSNAMES connection style.  I was able to make this work by adding another check in the DatabaseConnector.R for oracle.  Here's my patch:
```
---
 R/DatabaseConnector.R |    5 ++++-
 1 files changed, 4 insertions(+), 1 deletions(-)

diff --git a/R/DatabaseConnector.R b/R/DatabaseConnector.R
index 3792136..e4d2112 100644
--- a/R/DatabaseConnector.R
+++ b/R/DatabaseConnector.R
@@ -197,7 +197,10 @@ connect.default <- function(dbms = "sql server", user, domain, password, server,
       sid = parts[2]
     }
     result <- class(try(connection <- RJDBC::dbConnect(driver, paste("jdbc:oracle:thin:@",host,":",port,":",sid ,sep=""), user, password),silent=TRUE))[1]
-    
+
+    # JNix...try again...
+    if (result =="try-error")
+      result <- class(try(connection <- RJDBC::dbConnect(driver, paste("jdbc:oracle:thin:@",server,sep=""), user, password),silent=TRUE))[1]
     
     # Next try OCI driver:
     if (result =="try-error")
-- 
```

**Comment by schuemie** [comment]
Ok, I just added this, but I do not have a setup to test it. Would you be so kind?

I don't like the fact that you and anyone else using TNSNames will have a delay when connecting because the DatabaseConnector will first need to try and fail the other options, but I currently don't see an easy solution. Any ideas?

**Comment by nixl5s** [comment]
The change does work.  I agree I do not like the delay either.  Without introducing another variable, or performing some inspection of the server value to see if it contains something like a tnsname, I don't know any way around it.  I guess if we tried to inspect to see if the server variable is a tnsname, we could check to see if it contains the words "description" and "address", and if it did, bypass the first connection attempt.

That said, the change has at least allowed me to use TNSNAMES style connections, which in my case is required as I am connecting to a clustered environment with primary and failover nodes (all defined in the TNSNAMES entry).

I appreciate the help.

_____________________________________________
Jeremy Nix
Senior Application Developer
Biomedical Informatics
Cincinnati Children's Hospital Medical Center
513-803-2764 / Jeremy.Nix@cchmc.org<mailto:Jeremy.Nix@cchmc.org>

On 06/02/2015 07:10 PM, Martijn Schuemie wrote:

Ok, I just added this, but I do not have a setup to test it. Would you be so kind?

I don't like the fact that you and anyone else using TNSNames will have a delay when connecting because the DatabaseConnector will first need to try and fail the other options, but I currently don't see an easy solution. Any ideas?

**Comment by jduke99** [comment]
I am running into this problem. I can connect via Thin from SQL Developer but trouble using DatabaseConnector as it generates an error:

Error in .jcall(drv@jdrv, "Ljava/sql/Connection;", "connect", as.character(url)[1],  : 
  java.lang.UnsatisfiedLinkError: no ocijdbc11 in java.library.path

Here is my working Thin connection string that works from SQL developer:
jdbc:oracle:thin:@sasridg02.uits.iupui.edu:1521:I2B21STG

Can you provide me the proper format for setting up in DatabaseConnector?  This does not work:

connectionDetails <- createConnectionDetails(dbms="oracle", user="XXXXXX",password="XXXXXX", server="sasridg02.uits.iupui.edu", port="1521", schema="OMOPV5_DE")

Thanks!

**Comment by jduke99** [comment]
Sorry, got it working with this:

connectionDetails <- createConnectionDetails(dbms="oracle", user="XXXX",password="XXXXX", server="sasridg02.uits.iupui.edu/I2B21STG", port="1521", schema="OMOPV5_DE")

**Comment by aaron0browne** [comment]
Due to the method of falling back on successive Oracle connection methods, it is often very difficult to debug this because the error message always arises from the failure of the thick client to connect (the last method tried). +1 for better error reporting in this little piece.

**Comment by schuemie** [comment]
The latest version of DatabaseConnector (1.5.0) introduces two improvements:
1. Added a `oracleDriver` argument to `connect` and `createConnectionDetails` where the user can specify "thin" or "oci"
2. Fallback to TNSNames is no longer silent, so the user will see 'informative' error messages when something goes wrong.
