### ISSUE TITLE
Add loadMissingJdbcDriver function?

### ISSUE THREAD

**Issue by alondhe** [OHDSI/DatabaseConnector#120]
Hi @schuemie -- this is purely a nice-to-have, but I was wondering if for dialects in which the JDBC drivers are licensed and not open source (and therefore not in DatabaseConnectorJars) if we could offer a function to let users upload the driver into the library. This way, the user wouldn't have to keep including the path to the driver. It would just be available in the DatabaseConnectorJars library path just like the other drivers.

```
loadMissingJdbcDriver <- function(pathToDriver) {
  # installs into DatabaseConnectorJars library path
}
```

I'm wondering if you're on board with this as an idea. If so, I can make a PR.

**Comment by schuemie** [comment]
A nice idea, but unfortunately writing to the package library is against CRAN rules. 

We could use an environmental variable to specify the location of the JDBC driver. Users could then set the environmental variable in their '.renviron' file and never have to worry about it again. I did this already for the Windows authentication DLL. All that would be required is defaulting the driver location argument to this environmental variable.

**Comment by schuemie** [comment]
@alondhe : Since v4.0.0 we have `downloadJdbcDrivers()`, which for some platforms downloads the drivers from a [GitHub Pages site](https://ohdsi.github.io/DatabaseConnectorJars/). For other platforms, we could either:
- Add them to the GitHub pages site if their license allows (preferred)
- Add URLs to the JAR file on the provider's download page if downloading the driver doesn't require you to log in

Are there platforms for which we could use one of these options?
