### ISSUE TITLE
Int64 Data Returns as Numeric from BigQuery and Drops Digits

### ISSUE THREAD

**Issue by CartWill** [OHDSI/DatabaseConnector#121]
In our OMOP dataset, our ID numbers are stored as INT64 types.  Trying to download and match up some data  I noticed the data returned was dropping digits.

Expected Result:
```
> options("scipen" = 20)
> conn <- connect(connectionDetails)
Connecting using BigQuery driver
> result <- querySql(conn, "select cast(1234567890123456789 as int64) as test_column")
> result[1]
          TEST_COLUMN
1 12345678901234567689
```

Actual Result
```
> options("scipen" = 20)
> conn <- connect(connectionDetails)
Connecting using BigQuery driver
> result <- querySql(conn, "select cast(1234567890123456789 as int64) as test_column")
> result[1]
          TEST_COLUMN
1 1234567890123456768
```

**Comment by schuemie** [comment]
This is because R natively does not support 64-bit integers. As discussed [here](https://github.com/OHDSI/DatabaseConnector/issues/81), we should probably use the `bit64` package for this, just like as [RSQLite](https://github.com/r-dbi/RSQLite). This has been on my wishlist for a while, but haven't gotten around to.

**Comment by CartWill** [comment]
Thanks.  Since its just ID numbers we'll just have to know to cast them as strings before bringing them into R.

**Comment by schuemie** [comment]
Since v4.0.0 the default behavior is to still convert BIGINT to R's numeric type, but throw an error if that leads to loss of information (due to the loss of precision). You can opt to fetch the data as bit64::integer64, although that type is not consistently supported throughout R. Casting to string is probably still your best bet.
