### ISSUE TITLE
insertTable fails when input is tibble

### ISSUE THREAD

**Issue by schuemie** [OHDSI/DatabaseConnector#127]
The current code expects [subsetting to a column](https://github.com/OHDSI/DatabaseConnector/blob/master/R/InsertTable.R#L420) produces a vector, but for a tibble it creates another tibble.

Will need to use `dplyr::pull()` to convert to a vector, but this fails when the input is a `data.frame`, so must check type first.

**Comment by RowanErasmus** [comment]
The fix in the commit above does not solve the issue (admittedly that was also where I started messing around at first ;-))

Changing lines 297 and 300 in InsertTable.R by adding an or `tibble::is_tibble(data)` condition to the if statements already present will do the trick.

Simple workaround for others facing this issue is to simply convert your tibble to a dataframe calling `as.data.frame(tibble)` before calling insertTable.

**Comment by schuemie** [comment]
This fix is currently still in the develop branch. When you say that it doesn't work, did you use that version? And what was the reason for the failure?

**Comment by RowanErasmus** [comment]
The context is like so:
I was initially stuck with a "Batch entry 0 INSERT INTO ... is of type integer but expression is of type character varying" exception due to the insert being done as a a single long string containing all the values from the column. Looking like this "(c(0,0,0,1, etc.)". 

So I checked out the code and started debugging it locally. I realised that the `data[start:end, i]` was not returning what it should and the call to the java app was defaulting to string (the last possibility in the else if chain) and calling the setString method with this long string containing all the values.

Then I started doing something similar to you did with calling `as.vector(t(column)` which does create some kind of vector but did not recoginize a date datatype I had and was only feeding the first value of the column to the java code. Getting pretty frustrated now I finally found this here and realised it was not the DatabaseConnector that had never worked but it was this tiddle thing (and line 110 [here](https://github.com/OHDSI/CommonEvidenceModel/blob/master/evidenceProcessingTranslated/R/buildStcm.R) was what never worked) Tried your fix but gave the same issue as the `as.vector(t(column)` not recognising the date data type making the same kind of vector (if there are even different kinds).

Now knowing it has to do with the tiddle I've just converted this tiddle data frama back to a data.frame kind of data.frame (i'm completely new to R so forgive if i'm not calling things as they should be) and all is well. As suggested this fix would also work in the place where you do the `if(!is.data.frame(data))` check (which returns false, because aparently tiddle is a data frame).

All in all it kept met from the street today :-)
