### ISSUE TITLE
PostgreSQL scram-sha-256 support

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/DatabaseConnector#130]
Recent version of PostgreSQL require a driver that supports scram-sha-256 and the one included with DatabaseConnector does not support this authentication.

Error Message:
SCRAM authentication is not supported by this driver. You need JDK >= 8 and pgjdbc >= 42.2.0 (not ".jre" versions)

Fix:
Update driver to non .jre version
https://jdbc.postgresql.org/download/postgresql-42.2.18.jar

I have only tested this driver with PostgreSQL 13, not sure if updating DatabaseConnector to this driver would cause issues with prior versions.

**Comment by schuemie** [comment]
We can update DatabaseConnectorJars to that version. At the same time we should update the JDBC drivers for the other platforms as well (we should have few updates to DatabaseConnectorJars, since it is considered a 'data package', exceeding the allowed 5MB size)

We should do extensive testing before we release that though.

**Comment by schuemie** [comment]
I just updated all JDBC drivers in the develop branch of DatabaseConnectorJars. @fdefalco : could you test this? 

Note that for Windows authentication you'll need to update your authentication dll.
