### ISSUE TITLE
connect to postgresql with schema and database

### ISSUE THREAD

**Issue by nadavrap** [OHDSI/DatabaseConnector#144]
I'm trying to use DatabaseConnnector to connect to my PostgreSQL server. I can't find the right way to specify the database AND schema (in PostgreSQL, in a database there may be several schemas).
I tried to specify a database named `omop` and schema named `cdm_v5` as follow:

`connectionDetails <- createConnectionDetails(dbms="postgresql", 
                                             server="localhost/omop",
                                             user="postgres",
                                             password="mypass",
                                             schema="cdm_v5")`
But i get  the next error:

> Error in createConnectionDetails(dbms = "postgresql", server = "localhost/omop",  : 
>  unused argument (schema = "cdm_v5")

What is the right syntax?
I may connect, then send a `set search_path cdm_v5` query, but then I lose the generic form of using DatabaseConnnector as it is specific to PostgreSQL.

**Comment by schuemie** [comment]
You're thinking about it the right way. It is just that we decided to drop the `schema` argument because this was something that couldn't be supported across platforms. Not all DBMDs have the equivalent of `SET SEARCH_PATH` or `USE`.

Instead, the recommendation is to always explicitly specify the schema in your queries. So to connect you would use:
```r
connectionDetails <- createConnectionDetails(dbms="postgresql", server="localhost/omop", user="postgres", password="mypass")
connection <- connect(connectionDetails)
```

And then in your queries you would do something like this:
```r
renderTranslateQuerySql(connection, "SELECT COUNT(*) FROM @schema.my_table", schema = "cdm_v5")
```

That way the same code will run across all platforms.
