### ISSUE TITLE
Snowflake dialect support

### ISSUE THREAD

**Issue by alex-odysseus** [OHDSI/DatabaseConnector#197]
To unblock https://github.com/OHDSI/WebAPI/pull/2073

**Comment by schuemie** [comment]
@alex-odysseus : Your code [references the JDBC drivers on the DatabaseConnectorJar pages](https://github.com/OHDSI/DatabaseConnector/blob/develop/R/Drivers.R#L97). Could you create a PR for DatabaseConnectorJars adding `SnowflakeV3.13.22.zip` [here](https://github.com/OHDSI/DatabaseConnectorJars/tree/main/docs)? Currently we're failing a unit test because the driver cannot be downloaded.

**Comment by alex-odysseus** [comment]
Thank you for bringing this up, Martijn @schuemie 

Here it is https://github.com/OHDSI/DatabaseConnectorJars/pull/11
