### ISSUE TITLE
subsetting the database

### ISSUE THREAD

**Issue by tiozab** [OHDSI/DatabaseConnector#259]
Is there a way with which I can subset the database into chunks of 1 million e.g.?
I am asking this because the pregnancy algorithm does not run through in the entire CPRD, but it runs through in a subset of 100 k. 
If I could subset the database into chunks, I could run the algorithm in those chunks, save the output and then put the output back together to have the full output of all pregnancies.

**Comment by ablack3** [comment]
Is the pregnancy algorimthm written in SQL and running on the database or is it running in R or python?

**Comment by tiozab** [comment]
it is written in SQL and runs in R.
https://github.com/oxford-pharmacoepi/pregnancyAlgorithm_postgresql

**Comment by schuemie** [comment]
OMG! Those are a lot of steps! Do you happen to know which step(s) are the problem?

Which database platform are you using? Postgres?

**Comment by tiozab** [comment]
Yes!
It hangs in step 3.2

**Comment by ablack3** [comment]
I don't think this is really an issue with DatabaseConnector. In the code the executes the algorithm you can add batch processing by partitioning the CDM by person_id. So maybe run the algorithm for 1000 persons at a time or something like that. Then just combine the result table into one table.  Does that make sense?

**Comment by tiozab** [comment]
yes that is what I wanted to know, how to partition the CDM in database connector, I know there is the option in CDMConnector, but in database connector? I did not find anything in the manual that indicates a batch processing. @ablack3

**Comment by ablack3** [comment]
Well in a general sense I would first create a table in the database with two columns: person_id, batch_id. Where batch_id would be a random integer between 1 and 10 (for 10 batches). Then make sure to join to that table when executing the algorithm and use a where clause to select the appropriate partition. That's how I would approach it. This doesn't have anything to do with DatabaseConnector though since you are just using it to send SQL to the database. The batch process has to be coded in your algorithm. Maybe send me a message on Teams if you'd like help writing this. That's my two cents anyway.

**Comment by tiozab** [comment]
Thanks @ablack3 I used indexes and the code ran in a jiffy ;-)

**Comment by ablack3** [comment]
Nice!
