### ISSUE TITLE
Postgres timestamps without timezones datatype have timezones when data is downloaded into R

### ISSUE THREAD

**Issue by egillax** [OHDSI/DatabaseConnector#274]
I was debugging an issue where dates of the observation window were shifted for some of the patients in a cohort. 

I think I have narrowed it down to improper handling of the datatype `timestamp without timezone` in postgres (datatype described [here](https://www.postgresql.org/docs/current/datatype-datetime.html). Not sure if it's something in the jdbc driver (I'm using the version downloaded by DatabaseConnector) or in this package. Somewhere along the way my local timezone is added to it which causes the dates to shift when calling `as.Date` on it.

I've made a reprex below.  This is causing an issue in ApolloR where I want the covariates to be up to and including the index date, but for many cases the dates are shifted 1 day so that's not the case. This doesn't happen in PLP because I think there the date/timestamp isn't extracted to R, only the relative difference to the index date. 

@schuemie could you have a look? 

``` r
library(DatabaseConnector)

# the docker postgresql container started with:
# docker run --name postgres -e POSTGRES_PASSWORD=pass -d -p 5433:5432 postgres  
connectionDetails <- createConnectionDetails(dbms = "postgresql",
                                             server = "localhost/postgres",
                                             port=5433,
                                             user = "postgres",
                                             password = "pass",
                                             pathToDriver = "~/database_drivers/postgres/")

connection <- connect(connectionDetails)
#> Connecting using PostgreSQL driver

querySql(connection, "SELECT pg_typeof(date '2001-09-28' + interval '1 day') AS result_data_type;")
#>              RESULT_DATA_TYPE
#> 1 timestamp without time zone

result <- querySql(connection, "SELECT date '2001-09-28' + interval '1 day' AS result_value;")
print(result$RESULT_VALUE)
#> [1] "2001-09-29 CEST"


print(as.Date(result$RESULT_VALUE[1]))
#> [1] "2001-09-28"
```

<sup>Created on 2024-06-11 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by schuemie** [comment]
Should be fixed now in the develop branch

**Comment by schuemie** [comment]
Sorry, that 'fix' broke things in a lot of different places. In a way, DatabaseConnector is not doing anything wrong. It receives a datetime from the server with no timezone information, and since R requires a datatime to have a timezone it assumes the local timezone. One of the pleasant consequences is that if you upload data from a timezone, and download it in the same timezone, you get the same datetime back.

But R itself does something weird in `as.Date()`, where it transforms the datetime to the UTC timezone. This leads to inconsistencies in R itself:

```r
as.Date(as.POSIXct("2000-01-01"))
# [1] "1999-12-31"
```

Note that if you provide an empty string for `as.Date()` `tz` argument, you get the behavior I would expect:

```r
as.Date(as.POSIXct("2000-01-01"), tz = "")
# [1] "2000-01-01"
```

There are two possible fixes I can recommend for ApolloR:

1. Add explicit casts to dates in the SQL, e.g.

    ```sql
    CAST(DATEADD(DAY, @window_start, cohort_start_date)  AS DATE)
    ```

2. Don't let `as.Date()` convert to UTC, e.g.

    ```r
    as.Date(column, tz = "")
    ```

I prefer option 1 because it avoids the whole datetime differences between server and client altogether.

**Comment by egillax** [comment]
Thanks for the explanation. I'll add the date casts in SQL to ApolloR.
