### ISSUE TITLE
add a specific function to DatabaseConnector to list all the tables in a schema

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/DatabaseConnector#29]
per discussion here https://github.com/OHDSI/SqlRender/issues/36

this would be GREAT new addition!
@schuemie

**Comment by vojtechhuser** [comment]
Just posting another comment  draw attention to it. I would be really greatful if this would be added. @schuemie

**Comment by schuemie** [comment]
Please try the latest version, which has the `getTableNames` function. Let me know if this fits your needs.

**Comment by vojtechhuser** [comment]
thank you. I tried it. (and works)

 I wish this would be part of a release and I can require this version of package by DataQuality package. @schuemie

**Comment by schuemie** [comment]
For the R packages I don't really use the official GitHub release mechanism if that is what you mean, because I don't really see the point (until we get them in CRAN). I did increase the version number of the package when I added this new functionality from 1.7.1 to 1.8.0, so you can require (>= 1.8.0) in the DataQuality package.
