### ISSUE TITLE
Efficiency issues in retrieving large #records

### ISSUE THREAD

**Issue by writetoritu** [OHDSI/DatabaseConnector#3]
We are testing the DatabaseConnector package (on a Postgres database) to retrieve a table with over 25 million records.  It's taking about an hour to retrieve all the records with batch size of 100,000 (in dbGetQueryBatchWise function). Increasing the batch size (to 200,000 and above), while hoping to speed up the process, is leading to out of memory exceptions.  

Please let us know if there are any suggestions for configuration settings?

**Comment by schuemie** [comment]
Pfew, this took a looooooong time to debug, but I think I got it now. Having to restart R after every query is not desired behavior. It seems there were multiple things wrong, but most importantly there was a bug in the RJDBC package on which we depend. Luckily, the bug was already fixed a few weeks ago, and the current version in CRAN is fine. Commit 2dd61afef11d3f3bc15cc3c62423923de42541ea should fix the memory problem, although you'll also need to update RJDBC. Please follow these steps:
1. Close all instances of R
2. Open 1 instance of R
3. Run this code:
```r
remove.packages("RJDBC")
remove.packages("DatabaseConnector")
install.packages("RJDBC")
library(devtools)
install_github("ohdsi/DatabaseConnector")
```
After that, you should be able to run large queries again and again without needing to restart.

*Important:* I've renamed the `dbGetQueryBatchWise` function to `dbGetQueryPostgreSql`, since it's no longer using batches (and the `batchSize` parameter has also been dropped). In general, it is preferred to use `querySql` instead, which will call the `dbGetQueryPostgreSql` function but also adds some debugging features.

Please let me know if this fixes your issues.

**Comment by schuemie** [comment]
I recommend using `querySql()` (for getting data) and `executeSql()` (for sending updates) for all DBMSs. These functions are designed to deal with the peculiarities of each platform.

**Comment by writetoritu** [comment]
just wanted to update that - we have tested your latest release on postgres and it's working perfectly fine (without any memory errors). The efficiency remains the same, however, e.g. 1 min to fetch 1 million rows - this might have to do with the #columns of the tables we are working with. Soon, we will also be testing on other DBMS e.g. Oracle and I will update you on our progress. 
Thanks!

**Comment by writetoritu** [comment]
Hi @schuemie  ... finally we got to test on Oracle DBMS and its failing on querySql(). we noticed querysql is calling the "dbGetQueryPostgreSql" function https://github.com/OHDSI/DatabaseConnector/blob/master/R/HelperFunctions.R#L298 

Is that correct for Oracle?

**Comment by schuemie** [comment]
Yes, I really should rename that function. It is no longer PostgreSQL-specific. 

Can you tell me what the error is?

**Comment by writetoritu** [comment]
Thanks a lot! We are discussing this issue [here](https://github.com/PEDSnet/Data-Quality/issues/26#issuecomment-76646679). I will get back to you regarding the error message.

**Comment by bunnell** [comment]
I am coming round to the belief that our problems are more memory than anything else. Just got a chance to try the latest version of the scripts and was able to get to the point of running the visit_occurrence report. We died there for lack of memory _after_ loading the table (~9.9 million records). Died while plotting (or preparing to):

> source("./scripts/GenerateVisit_OccurrenceReport.R")
[1] "2015-03-05 16:34:39 EST"
Loading required package: RJDBC
Loading required package: rJava
Connecting using Oracle driver
[1] 9895427
[1] "Plotting for Field:  visit_start_date"
Error: memory exhausted (limit reached?)

In discussing with Chris Pennington, we realized that this is a 32-bit VM (don't ask). The VM has 8 gig of memory, but apparently R maxes out at just of 3 gig on a 32-bit machine. Working with IT to get something more reasonable set up ASAP.

**Comment by schuemie** [comment]
Well, the good news is that this is not a Java error ;-)

It is saying R has run out of memory. I'm guessing you're using a 32-bit version of R?

You can use the `querySql.ffdf()` function to fetch the data to an ffdf object instead. This will prevent running out of memory, but might make processing the data later on more difficult (an ffdf object can be used a bit like a data.frame, but not entirely)

But maybe you should think about why you're fetching so much data?
