### ISSUE TITLE
Redshift and insertTable()

### ISSUE THREAD

**Issue by alondhe** [OHDSI/DatabaseConnector#34]
For Redshift's usage of insertTable(), there's this fragment:
```
else if (attr(connection, "dbms") == "oracle" | attr(connection, "dbms") == "redshift") {
        apply(data[start:end,
              drop = FALSE],
              statement = statement,
              isDate = isDate,
              MARGIN = 1,
              FUN = insertRowOracle)
```
It errors out with this message:
```
Error in `[.data.frame`(data, start:end, drop = FALSE) : 
  undefined columns selected
In addition: Warning message:
In `[.data.frame`(data, start:end, drop = FALSE) :
  'drop' argument will be ignored
```

I'm wondering if the code fragment for Redshift should be this, where there's a blank 2nd parameter in the call to data[]. This doesn't error out, and instead yields a data frame of the data you're trying to insert. 

```
else if (attr(connection, "dbms") == "oracle" | attr(connection, "dbms") == "redshift") {
        apply(data[start:end, ,
              drop = FALSE],
              statement = statement,
              isDate = isDate,
              MARGIN = 1,
              FUN = insertRowOracle)
```

**Comment by schuemie** [comment]
You are absolutely right. What amazes me is that no one stumbled on this bug before. Some detective work uncovers that  [I introduced this error on August 16](https://github.com/OHDSI/DatabaseConnector/commit/b426b2f6d4b745b4a8f1d330f236a4d1c7a45a24). Clearly no one has used this function on Oracle or RedShift since then. I will fix the bug shortly.

Just so you know, inserting data into RedShift via JDBC is insanely slow. If you have more than a few hundred rows of data you want to insert you should forget about it. This is a limitation of RedShift, there's nothing I can do about it.

**Comment by alondhe** [comment]
Oh good, glad this was the right fix then. Regarding inserting data, yeah, it's slow in both our MPP platforms (Redshift and PDW). I understand @jreps is working on introducing the usage of dwLoader potentially. I've used some custom code for the Janssen pregnancy algorithm to use COPY and S3 to bulk load data rather than use insert.
