### ISSUE TITLE
Connecting with Oracle driver

### ISSUE THREAD

**Issue by writetoritu** [OHDSI/DatabaseConnector#4]
Hi @schuemie 

We were able to successfully connect to Postgres (as mentioned [here](https://github.com/OHDSI/DatabaseConnector/issues/3)). However, we ran into the following error with Oracle: 

Connecting using Oracle driver
Jan 21, 2015 8:46:22 a.m. oracle.jdbc.driver.OracleDriver registerMBeans
WARNING: Error while registering Oracle JDBC Diagnosability MBean.
java.lang.NoSuchMethodError: method javax.management.StandardMBean. with signature (Ljava.lang.Class;Z)V was not found.
at oracle.jdbc.driver.OracleDiagnosabilityMBean.(OracleDiagnosabilityMBean.java:34)
at oracle.jdbc.driver.OracleDriver.registerMBeans(OracleDriver.java:367)
at oracle.jdbc.driver.OracleDriver$1.run(OracleDriver.java:201)
at java.security.AccessController.doPrivileged(libgcj.so.10)
at oracle.jdbc.driver.OracleDriver.(OracleDriver.java:197)
at java.lang.Class.initializeClass(libgcj.so.10)
at java.lang.Class.forName(libgcj.so.10)
Error in .jcall(drv@jdrv, "Ljava/sql/Connection;", "connect", as.character(url)[1], : 
java.lang.NoClassDefFoundError: oracle.jdbc.driver.T2CConnection

Would you have any insight on this? Thanks a lot for your help!

**Comment by writetoritu** [comment]
@schuemie update - we were able to make it work with Oracle driver after running "R CMD javareconf" 

However, we are unable to make it work with ODBC driver and getting the following errors - would you have any suggestions for us?: 

Error executing SQL: Error in inherits(obj, "jobjRef"): trying to get slot "jc" from an object of a basic class ("NULL") with no slots

An error report has been created at errorReport.txt
Error in value[3L] : no loop for break/next, jumping to top level

errorReport.txt

DBMS:

Error:
trying to get slot "jc" from an object of a basic class ("NULL") with no slots

**Comment by schuemie** [comment]
Sorry for the late response. I'm not sure I understand what you're trying to do. DatabaseConnector uses JDBC, and currently does not support ODBC. It seems there is some [built-in support for using ODBC through the JDBC api](http://docs.oracle.com/javase/1.5.0/docs/guide/jdbc/bridge.html) in Java so in theory we could add it. But usually ODBC connections only supports a subset of the functionality supported by the native and JDBC interfaces. 

Could you explain a bit more about what you're trying to do?

**Comment by writetoritu** [comment]
We are members of the [PEDSnet project](http://pedsnet.info/) project and developing some common scripts in R to conduct data quality checks across various sites (using different DBMS and platforms). We are using the DatabaseConnector package to establish DB connection. 

Here is an update on the abovementioned issues with "Oracle" driver: 
- Linux: we had to run the command "R CMD javareconf" on terminal to get rid of the errors mentioned [in my first comment](https://github.com/OHDSI/DatabaseConnector/issues/4#issue-55152626)
- Windows: In CreateConnectionDetails - the value for the "server" parameter specified as "sid" is working while , "host/sid" is not working. 
[reference line](https://github.com/OHDSI/DatabaseConnector/blob/master/R/DatabaseConnector.R#L68)

Thanks for your response.

**Comment by aaron0browne** [comment]
One clarification on the above is that the second bullet point, about windows, was on a machine running 64-bit java and oracle 12, so 64-bit R, a different ojdbc6.jar, and at least one PATH variable addition (to add a DLL) were all required. The relevant ticket is [here](https://github.com/PEDSnet/Data-Quality/issues/21#issuecomment-71712597). That's a private repo, so let me know if you don't already have access, @schuemie, I can't remember.

**Comment by schuemie** [comment]
The Oracle connectivity has been tested the least, mostly because I don't have a very sophisticated setup. So very sorry for all the trouble, and thanks for helping find the problems!

Just for clarification:

  1. Are you saying there are two versions of ojdbc6.jar available? 

  2. Can you tell me why `R CMD javareconf` fixed the errors? 

  3. The Oracle driver has two options for connecting. The *THIN* driver is tried first and requires the sid, next DatabaseConnector tries the *OCI* driver, which requires an Oracle client to be installed locally I think, and you can use a URL to connect to the database. In my setup I can only test THIN. Are you also using the THIN driver?

  4. Earlier you mentioned ODBC. Is ODBC support something your project requires?

@aaron0browne : I don't have access to that repo. Could you add me?

**Comment by aaron0browne** [comment]
I don't know very much about Oracle connectivity either, I'm just trying to parse the error reports we've gotten.

1. The user has the Oracle 12 client with 64-bit Java installed, and I believe one of these two things necessitated a different ojdbc6.jar, although with your number 3 above about THIN vs OCI drivers, that could have been a confounding factor, because the user also changed the calling signature from `connectionDetails <- createConnectionDetails(dbms=tolower(driver), server=paste(dbhost,"/",dbname,sep=""),user=dbuser,password=dbpass,schema=dbschema,port=dbport)` to `connectionDetails <- createConnectionDetails(dbms=tolower(driver), server=dbname,user=dbuser,password=dbpass,schema=dbschema,port=dbport)`, which could have implicitly toggled the driver used since one seems to pass a url as the server argument while the other passes an sid (didn't see the actual variable referents)?

2. So, the problem solved by `R CMD javareconf` was for a different user than the one in point 1. And while I don't know why specifically, I can only guess that the machine had some non-standard java setup?

3. As was probably clear as mud in point 1, I don't know which driver the user ended up with.

4. The mention of ODBC was a red herring that stemmed from mistaken conflation with an earlier connectivity problem while using a different library.

@schuemie I'll work on it and let you know here when you have access.

**Comment by writetoritu** [comment]
Thank you @aaron0browne for responding. 
I can only add to point (4) - as soon as I realized that the databaseconnector package doesn't handle ODBC, we asked the user to specify "Oracle" and not "ODBC" as the driver and that has worked just fine (ofcourse with the changes mentioned in points 1, 2, and 3).

**Comment by aaron0browne** [comment]
@schuemie invitation to the PEDSnet org and a team which gives you read access to all repos sent. That same link in my above comment will take you to the relevant issue once you have accepted the invite.
