### ISSUE TITLE
Add support for windows auth to sql server with jtds jdbc

### ISSUE THREAD

**Issue by kembree1** [OHDSI/DatabaseConnector#58]
The standard microsoft jdbc requires the installation of the sqljdbc_auth.dll, which only adds windows authentication to java running on windows clients.

If you simple add logic to allow the connectiondetails method to optionally capture (and pass through) of a 'domain' parameter in addition to the user and password parameters you already have then a user can install the jtds jdbc driver java and connect to sql server via windows authentication from all platforms, not just windows.

**Comment by schuemie** [comment]
We just removed jtds because no one was using it, and it handles dates incorrectly. I'm sorry, it is not coming back.

**Comment by cukarthik** [comment]
We depend on the jtds driver to allow us to do windows authentication b/c we have WebAPI instances running on a Linux box and hits a SQL Server database. We have found that the sqljdbc_auth.dll file does not work for us.

**Comment by chrisknoll** [comment]
The sqljdbc_auth.dll is definitely a win32 library, so I woudln't expect it to work on linux, but This is what I found as far as authentication with Active Directory on linux:
https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-active-directory-authentication?view=sql-server-linux-2017

Then, I found this article about setting up kerberos configuration to allow connections to a linux hosted sql server:
https://blogs.msdn.microsoft.com/psssql/2015/01/09/jdbc-this-driver-is-not-configured-for-integrated-authentication/

I think the information provided in both those articles should allow you to connect to sql server using JavaKerberos authentication.

-Chris

**Comment by chrisknoll** [comment]
In addition, I found an article about the latest JDBC drivers (v6.4) which seem to include new features for Azure AD Authentication on Linux, you may be able to use this new driver to get better results:
https://docs.microsoft.com/en-us/sql/connect/jdbc/system-requirements-for-the-jdbc-driver?view=sql-server-2017

**Comment by schuemie** [comment]
Just to provide some context for my perhaps brief rejection: The OHDSI developers are finding that the unlimited growth of supported platforms and drivers is causing serious headaches. For example, I remember spending quite some time on debugging issues related to using jtds instead of the Microsoft driver. From here on out I'll be the bad cop saying people should adhere to the standard, instead of expanding the standard.

**Comment by cukarthik** [comment]
I appreciate the need to limit things for support purposes. In that case, where should we raise this issue of not getting windows authentication to work from a Linux machine? I’m sure others have solved it but we weren’t able to get it to work without jtds.

Sent from my phone

On Jun 11, 2018, at 3:11 AM, Martijn Schuemie <notifications@github.com<mailto:notifications@github.com>> wrote:


Just to provide some context for my perhaps brief rejection: The OHDSI developers are finding that the unlimited growth of supported platforms and drivers is causing serious headaches. For example, I remember spending quite some time on debugging issues related to using jtds instead of the Microsoft driver. From here on out I'll be the bad cop saying people should adhere to the standard, instead of expanding the standard.

**Comment by schuemie** [comment]
I'm obviously not aware of the context here, but my first question would be to your DB admin. It seems that requiring Windows authentication in an environment with non-Windows machines is a bit odd. At the very least, creating one or a few login accounts that do not require Windows authentication but just regular username-password authentication should be trivial.

**Comment by chrisknoll** [comment]
I may be mistaken, but the context I understood was: they have a windows domain with Windows clients, but the WebAPI is hosted on a linux server, which needs to connect to mssql server (it's unclear if the mssql server is hosted on linux or not).  

I believe the solution is to leverage JavaKerberos authentication (the default is NativeAuthentication wich will attempt to levergae Win32API to get credentials, which won't work on linux).  But to get that all working, there's Kerberos setup, possibly the server needs to join the domain, you have to go through the steps of a SPN, etc.  It's non-trivial to be sure, but I think if you follow the links I gave or find documentation about a specific linux setup, it should be possible to use the JDBC driver from MS to authenticate.

This would be very good information to know (since we're seeing more heterogeneous environments with Linux and Microsoft tech) so if you do plan on going through the process of getting your linux to talk to SqlServer over kerberos auth, please write everything down and share your experience.

**Comment by chrisknoll** [comment]
@schuemie : there's one thing in DatabaseConnector that might need to be extended to allow additional paramaters to the JDBC url (I believe you construct the JDBC url behind the scenes):

In order to use non-native authentication, you need to pass additional properties, listed here:
https://docs.microsoft.com/en-us/sql/connect/jdbc/setting-the-connection-properties?view=sql-server-2017

I'm wondering if there's a way to provide an additional parameter to databaseConnector that will let you send in a list of urlArgs that can just be appended to the JDBC URL during connection...

**Comment by t-abdul-basser** [comment]
I have to agree with @kembree1 and advocate that we support jTDS driver in DatabaseConnector so that we can cover the important scenario that @cukarthik outlined above, namely, authenticating in a Linux environment against SQL Server (on Windows) using windows/native authentication. Think Docker container (Broadsea)! 
@chrisknoll Setting up Kerberos in order to support this common scenario when a JDBC driver exits that supports it out of the box with the additional of a single JDBC URL parameter seems...onerous. 
@schuemie  DBAs In our department, DBA prefer to configure SQL Server DBs to support native authentication and are in fact required by data security policies to do so.
@schuemie If there is a date type handling issue then perhaps we can re-visit and try to workaround it?

**Comment by chrisknoll** [comment]
Last thing I can add on this:
https://confluence.atlassian.com/bitbucketserver/transitioning-from-jtds-to-microsoft-s-jdbc-driver-776640388.html

See section on 'Why Change Drivers?'  Interesting part:

> Since jTDS 1.3.1 does not provide a functioning JDBC4 implementation, the decision was made to replace jTDS with Microsoft's own SQL Server driver. Microsoft's driver is actively maintained, where jTDS hasn't been updated since 2014 (and prior to the small round of updates done in 2014 it hadn't been updated for multiple years).

**Comment by schuemie** [comment]
@chrisknoll : you can add properties to the connection string in two ways:

1. Use the `extraSettings` argument of `createConnectionDetails` or `connect`. The contents of this argument will simply be appended to the connection string constructed by DatabaseConnector (with a semicolon inbetween).

2. Use the `connectionString` argument of `createConnectionDetails` or `connect` to completely specify the connection string yourself.

See [the logic here](https://github.com/OHDSI/DatabaseConnector/blob/master/R/Connect.R#L237).

@t-abdul-basser : one bug that has already been reported in jtds in 2012 and hasn't been fixed since (proving @chrisknoll 's last point) is [the inability of jtds to recognize dates](https://sourceforge.net/p/jtds/bugs/679/), which in OHDSI is kind of a big thing.
