### ISSUE TITLE
PDW: sql account credentials not working in dwloader

### ISSUE THREAD

**Issue by alondhe** [OHDSI/DatabaseConnector#60]
https://github.com/OHDSI/DatabaseConnector/blob/master/R/InsertTable.R#L439

This conditional doesn't actually pull the user name and password from a connection object.

**Comment by alondhe** [comment]
Hi @schuemie,

This bug is about being able to pass a Connection object to insertTable and run the MPP bulk load (via a command line execution of dwLoader). If you are using a SQL account (not Windows auth), we cannot parse the password from the connection object to then embed as a parameter in the dwLoader call. 

A few questions:

1. Is there actually a way to parse the password from the JDBC Connection? I can get the user, but not the password.
2. Assuming that we can't parse the password from the Connection, would you be against letting users pass in a connectionDetails object instead of a Connection object to insertTable?
3. Or, should we do a hack, like rely upon a system env variable for the password?

**Comment by schuemie** [comment]
1. There doesn't seem to be a way to get the password from the JDBC connection.
2. Nope, not going to allow a `connectionDetails` argument instead of `connection`.
3. Yes. Just like the AWS credentials would at least be consistent.

An alternative would be to add the user name and password to the R connection object ([just like `dbms` is currently a property](https://github.com/OHDSI/DatabaseConnector/blob/master/R/DBI.R#L65)). I somehow feel uncomfortable secretly carrying login credentials around, but it is already an open connection object anyway.
