### ISSUE TITLE
Support insert BIGINT

### ISSUE THREAD

**Issue by NEONKID** [OHDSI/DatabaseConnector#73]
The value range of INT is up to 2 ^ 31 - 1, so if you use numeric to call a larger value (such as BIGINT) as insertTable function, it is set to FLOAT value in DB (currently use SQL Server).

**Comment by schuemie** [comment]
Yes, I see the problem, but I'm not sure what the solution should look like. Unfortunately there's no equivalent of a BIGINT in R, and we have been using `numeric` fields to store integer values > 2^ 31 - 1. `insertTable` doesn't know which numeric fields are really BIGINTs, and which numeric fields are really FLOATs (or equivalent).

@NEONKID : do you have suggestions on how we inform `insertTable` which R numeric fields should become BIGINTs?

**Comment by chandryou** [comment]
I looks ugly.. But this is my solution to identify INT bigger than INT type in R

`
decimalplaces <- function(x) {
        if ((x %% 1) != 0) {
                strsplit(as.character(x),split =".", fixed =TRUE)[[1]][2]
        } else {
                return(0)
        }
}
#If x is 3.00, the return value from decimalplaces is not 0, which I intended. 


maxIntR<-.Machine$integer.max
numBiggerThanIntR<-as.numeric(maxIntR) + 1L #maxIntR+1L returns error operation between integers should be int in R

#If x is an random number of integer
x<-floor(runif(1, min = -maxIntR, max = maxIntR))
x<-as.integer(x)

if (is.numeric(x) & is.integer(x)) print ("x is integer")

#If x is an random number of integer bigger than maxIntR
x<-floor(runif(1, min = maxIntR, max = as.numeric(maxIntR)+10000L))

if (is.numeric(x) & !is.integer(x) & abs(x)>maxIntR & decimalplaces(x)==0) print ("x is BigINT")

#Otherwise? then x would be float.`

**Comment by chandryou** [comment]
The shorter version is possible like below. 
Still, in this case, if x=3.00, it is classified into 'integer'. But the algorithm above classifies x as float, which I prefer. 
```
maxIntR<-.Machine$integer.max
numBiggerThanIntR<-as.numeric(maxIntR) + 1L #maxIntR+1L returns error operation between integers should be int in R

#If x is an random number of integer
x<-floor(runif(1, min = -maxIntR, max = maxIntR))
x<-as.integer(x)

if (is.numeric(x) & is.integer(x)) print ("x is integer")

#If x is an random number of integer bigger than maxIntR
x<-floor(runif(1, min = maxIntR, max = as.numeric(maxIntR)+10000L))
if (is.numeric(x) & !is.integer(x) & abs(x)>maxIntR & x%%1 ==0 ) print ("x is BigINT")
```

**Comment by NEONKID** [comment]
```R
is.bigint <- function(x) {
    num <- 9223372036854775808
    
    bigint.min <- -num
    bigint.max <- num - 1
    
    return(x == round(x) && x >= bigint.min && x <= bigint.max)
}
```
I think that the scope of BIGINT is mostly in the range of long in Java.

Therefore, it is better to insert the BIGINT value by the above code.

The bit64 package or the gmp (GIMP) package also supports integer64 range values, but most of the time, they were not able to determine the decimal number.
